"""
Django settings for library_system project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g(p@77ai!yd-v%9sc^&!#@3^ndu=#f2w(y*fnii_r$fzjjim3o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'core',
]
# 2. Bật chế độ xác thực bằng JWT cho toàn dự án
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'library_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.dashboard_stats',
                'core.context_processors.notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'alovu_library', # Tên database chúng ta sẽ tạo trên XAMPP
        'USER': 'root',          # User mặc định của XAMPP
        'PASSWORD': '',          # Pass mặc định của XAMPP là rỗng
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', names 'utf8mb4'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'

STATIC_URL = '/static/'
# Khai báo đường dẫn thư mục static chung của toàn dự án
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

JAZZMIN_SETTINGS = {
    "site_title": "Admin Alovu",
    "site_header": "Alovu Library",
    "site_brand": "Thư viện Alovu",
    "welcome_sign": "Chào mừng Khanh đến với hệ thống quản trị",
    "copyright": "Alovu Library",
    "search_model": ["core.Book", "core.User"], 
    "custom_js": "js/admin_chart.js",

    
    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index", "permissions": ["core.view_user"]},
        {"name": "Thoát hệ thống", "url": "/logout/", "icon": "fas fa-sign-out-alt", "new_window": False},
        {"model": "core.User"},
    ],
    
    "user_menu_links": [
        {"name": "Thoát", "url": "/logout/", "icon": "fas fa-power-off text-danger"},
    ],
    
    "order_with_respect_to": [
        "core.Book", "core.Category", "core.Publisher", "core.BookImage",
        "core.BorrowTransaction", "core.Penalty", 
        "core.User", "core.Membership", "core.Wishlist", "core.Recommendation",
        "core.Review", "core.Notification", "core.ChatRoom", "core.Chat"
    ],

    # [BỔ SUNG] GẮN ICON CHO TỪNG BẢNG ĐỂ MENU BÊN TRÁI ĐẸP HƠN
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.Book": "fas fa-book",
        "core.Category": "fas fa-tags",
        "core.Publisher": "fas fa-building",
        "core.BookImage": "fas fa-images",
        "core.BorrowTransaction": "fas fa-exchange-alt",
        "core.Penalty": "fas fa-money-bill-wave",
        "core.User": "fas fa-user-graduate",
        "core.Membership": "fas fa-medal",
        "core.Wishlist": "fas fa-heart",
        "core.Recommendation": "fas fa-thumbs-up",
        "core.Review": "fas fa-star",
        "core.Notification": "fas fa-bell",
        "core.ChatRoom": "fas fa-comments",
        "core.Chat": "fas fa-comment-dots"
    },
    
    # Icon mặc định nếu bảng nào chưa được gắn
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    
    "changeform_format": "vertical_tabs", 
    "default_theme_mode": "light", 
    "show_ui_builder": False,
}

# (Đoạn JAZZMIN_UI_TWEAKS của bạn giữ nguyên, màu cam rất đẹp rồi)
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-white navbar-light", 
    "brand_colour": "navbar-orange",
    "accent": "accent-orange",
    "sidebar": "sidebar-dark-primary",
    
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
# Khi gọi hàm logout, hệ thống sẽ tự tìm đến URL có name='login'
LOGOUT_REDIRECT_URL = 'login'

# CẤU HÌNH GỬI EMAIL QUA GMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Điền email dùng để GỬI TIN ĐI (Có thể dùng chính email của bạn)
EMAIL_HOST_USER = 'tuananhih271@gmail.com' 

# MẬT KHẨU ỨNG DỤNG (Lưu ý: Không phải mật khẩu đăng nhập Gmail)
EMAIL_HOST_PASSWORD = 'ytzc xuks imdn xgpt' 

DEFAULT_FROM_EMAIL = 'Thư viện Alovu <tuananhih271@gmail.com>'

# Sửa 'en-us' thành 'vi'
LANGUAGE_CODE = 'vi'

# Đảm bảo cài đặt i18n đang được bật
USE_I18N = True
USE_TZ = True

# 3. Cấu hình thời gian sống của Token (Nên để ở cuối file)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Access token sống 60 phút
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Refresh token sống 7 ngày
    'AUTH_HEADER_TYPES': ('Bearer',),               # Chuẩn header: Authorization: Bearer <token>
}

# Thêm vào cuối file
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', 'your-api-key-here')