"""
Django settings for library_system project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
import os


# Xây dựng đường dẫn bên trong dự án như sau: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Cài đặt khởi động nhanh - không phù hợp cho môi trường sản xuất
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# CẢNH BÁO BẢO MẬT: Hãy giữ bí mật khóa bí mật được sử dụng trong môi trường sản xuất!
SECRET_KEY = 'django-insecure-g(p@77ai!yd-v%9sc^&!#@3^ndu=#f2w(y*fnii_r$fzjjim3o'

# CẢNH BÁO AN NINH: Không nên chạy với chế độ gỡ lỗi được bật trong môi trường sản xuất!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'core',
]
# 2. Bật chế độ xác thực bằng JWT cho toàn dự án
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'library_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.dashboard_stats',
                'core.context_processors.global_counts',
                'core.context_processors.notifications_count',
                'core.context_processors.show_borrow_info',
                'core.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'alovu_library', # Tên database chúng ta sẽ tạo trên XAMPP
        'USER': 'root',          # User mặc định của XAMPP
        'PASSWORD': '',          # Pass mặc định của XAMPP là rỗng
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', names 'utf8mb4'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'

STATIC_URL = '/static/'
# Khai báo đường dẫn thư mục static chung của toàn dự án
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# JAZZMIN_SETTINGS = {
#     "site_title": "Admin Alovu",
#     "site_header": "Alovu Library",
#     "site_brand": "Thư viện Alovu",
#     "welcome_sign": "Chào mừng bạn đến với hệ thống quản trị",
#     "copyright": "Alovu Library",
#     "search_model": ["core.Book", "core.User"], 
#     "custom_js": "js/admin_chart.js",
#     "custom_css": "css/admin_custom_v1.css",
#     "topmenu_links": [
#         {"name": "Trang chủ", "url": "admin:index", "permissions": ["core.view_user"]},
#         {"name": "Thoát hệ thống", "url": "/logout/", "icon": "fas fa-sign-out-alt", "new_window": False},
#         {"model": "core.User"},
#     ],
    
#     "user_menu_links": [
#         {"name": "Thoát", "url": "/logout/", "icon": "fas fa-power-off text-danger"},
#     ],
    
#     "order_with_respect_to": [
#         "core.Book", "core.Category", "core.Publisher", "core.BookImage",
#         "core.BorrowTransaction", "core.Penalty", 
#         "core.User", "core.Membership", "core.Wishlist", "core.Recommendation",
#         "core.Review", "core.Notification", "core.ChatRoom", "core.Chat"
#     ],

#     # [BỔ SUNG] GẮN ICON CHO TỪNG BẢNG ĐỂ MENU BÊN TRÁI ĐẸP HƠN
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#         "core.Book": "fas fa-book",
#         "core.Category": "fas fa-tags",
#         "core.Publisher": "fas fa-building",
#         "core.BookImage": "fas fa-images",
#         "core.BorrowTransaction": "fas fa-exchange-alt",
#         "core.Penalty": "fas fa-money-bill-wave",
#         "core.User": "fas fa-user-graduate",
#         "core.Membership": "fas fa-medal",
#         "core.Wishlist": "fas fa-heart",
#         "core.Recommendation": "fas fa-thumbs-up",
#         "core.Review": "fas fa-star",
#         "core.Notification": "fas fa-bell",
#         "core.ChatRoom": "fas fa-comments",
#         "core.Chat": "fas fa-comment-dots",
#         "core.Event": "fas fa-calendar-alt",          
#         "core.EventRegistration": "fas fa-ticket-alt",  
#     },
    
#     # Icon mặc định nếu bảng nào chưa được gắn
#     "default_icon_parents": "fas fa-folder",
#     "default_icon_children": "fas fa-circle",
    
#     "changeform_format": "vertical_tabs", 
#     "default_theme_mode": "light", 
#     "show_ui_builder": False,
#     # Ẩn các bảng phụ khỏi menu chính để đỡ rối
#     "hide_models": [
#         "core.BookImage", 
#         "core.Cart", 
#         "core.CartItem",
#         "core.EventRegistration", # Quản lý đăng ký bên trong chi tiết Event sẽ hợp lý hơn
#         "core.ChatMessage",
#         "core.ChatRoom", 
#         "core.Chat",
#         "core.ChatMessage", # Bạn nên ẩn luôn cả ChatMessage nếu không dùng trực tiếp
#     ],
#     "hide_apps": ["auth"],
# }

# JAZZMIN_UI_TWEAKS = {
#     "navbar": "navbar-white navbar-light",
#     "theme": "flatly", # Theme phẳng, màu sắc hiện đại, nhẹ nhàng hơn
#     "sidebar": "sidebar-dark-primary",
#     "sidebar_nav_compact_style": True, # Thu gọn khoảng cách giữa các dòng menu bên trái
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": True,    # Bỏ viền bo cong của menu, trông cứng cáp hơn
#     "sidebar_disable_expand": False,
#     "layout_boxed": False,
#     "sidebar_fixed": True,             # Cố định thanh menu bên trái khi cuộn chuột
#     "navbar_fixed": True,              # Cố định thanh điều hướng phía trên
    
#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     }
# }

# --- CẤU HÌNH CƠ BẢN SIMPLEUI ---

SIMPLEUI_INDEX = '/admin/'
SIMPLEUI_HOME_PAGE = '/admin-dashboard/'

SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_QUICK = False   # Trạng thái ban đầu của bạn là True, hãy đổi thành False
SIMPLEUI_HOME_ACTION = False
SIMPLEUI_ANALYSIS = False


SIMPLEUI_LOGO = 'https://cdn-icons-png.flaticon.com/512/1508/1508555.png'

# Tương đương site_title, site_header, welcome_sign của Jazzmin
SIMPLEUI_HOME_TITLE = 'Alovu Library' 
SIMPLEUI_HOME_PAGE_NAME = 'Bàn Làm Việc' # Thay chữ "Trang chủ" mặc định
SIMPLEUI_HOME_ICON = 'fas fa-home'

# --- TỐI ƯU GIAO DIỆN & TỐC ĐỘ ---
SIMPLEUI_STATIC_OFFLINE = True # Tải file tĩnh nội bộ (Giúp load nhanh hơn)
SIMPLEUI_LOADING = True        # Hiện loading khi chuyển tab cho mượt
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css' # Hoặc 'ant.design.css' - Theme phẳng, hiện đại giống 'flatly' của Jazzmin

# --- CẤU HÌNH MENU SIMPLEUI ---
SIMPLEUI_CONFIG = {
    # Tắt menu mặc định của Django, chỉ dùng menu tự định nghĩa phía dưới
    # Đây là cách TỐT NHẤT để ẩn 'auth', 'BookImage', 'Cart', 'ChatRoom'... như bạn muốn bên Jazzmin
    'system_keep': False, 
    'dynamic': False,     
    
    # Khai báo cấu trúc Menu
    'menus': [
        {
            'name': 'Quản lý Kho Sách',
            'icon': 'fas fa-book-reader',
            'models': [
                {'name': 'Kho Sách', 'url': 'core/book/', 'icon': 'fas fa-book'},
                {'name': 'Danh mục sách', 'url': 'core/category/', 'icon': 'fas fa-tags'},
                {'name': 'Nhà xuất bản', 'url': 'core/publisher/', 'icon': 'fas fa-building'},
            ]
        },
        {
            'name': 'Mượn Trả & Dịch Vụ',
            'icon': 'fas fa-exchange-alt',
            'models': [
                {'name': 'Giao dịch mượn sách', 'url': 'core/borrowtransaction/', 'icon': 'fas fa-hand-holding'},
                {'name': 'Quản lý Phạt', 'url': 'core/penalty/', 'icon': 'fas fa-money-bill-wave'},
                {'name': 'Sự kiện (Events)', 'url': 'core/event/', 'icon': 'fas fa-calendar-alt'},
            ]
        },
        {
            'name': 'Tương tác Bạn đọc',
            'icon': 'fas fa-users-cog',
            'models': [
                {'name': 'Đánh giá (Reviews)', 'url': 'core/review/', 'icon': 'fas fa-star'},
                {'name': 'Sách yêu thích', 'url': 'core/wishlist/', 'icon': 'fas fa-heart'},
                {'name': 'Gợi ý sách', 'url': 'core/recommendation/', 'icon': 'fas fa-thumbs-up'},
            ]
        },
        {
            'name': 'Hệ Thống & Người Dùng',
            'icon': 'fas fa-cogs',
            'models': [
                {'name': 'Học viên / Người dùng', 'url': 'core/user/', 'icon': 'fas fa-user-graduate'},
                {'name': 'Thẻ Thành viên', 'url': 'core/membership/', 'icon': 'fas fa-medal'},
                {'name': 'Thông báo', 'url': 'core/notification/', 'icon': 'fas fa-bell'},
                # Link thoát hệ thống giống topmenu_links của Jazzmin
                #{'name': 'Thoát hệ thống', 'url': '/logout/', 'icon': 'fas fa-sign-out-alt'} 
            ]
        }
    ]
}

LOGOUT_ON_GET = True

# Đường dẫn trang login của bạn
LOGIN_URL = '/login/'

# Sau khi logout thì quay về trang login này
LOGOUT_REDIRECT_URL = '/login/'

# Khi gọi hàm logout, hệ thống sẽ tự tìm đến URL có name='login'
# LOGOUT_REDIRECT_URL = 'login'

# CẤU HÌNH GỬI EMAIL QUA GMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Điền email dùng để GỬI TIN ĐI (Có thể dùng chính email của bạn)
EMAIL_HOST_USER = 'tuananhih271@gmail.com' 

# MẬT KHẨU ỨNG DỤNG (Lưu ý: Không phải mật khẩu đăng nhập Gmail)
EMAIL_HOST_PASSWORD = 'ytzc xuks imdn xgpt' 

DEFAULT_FROM_EMAIL = 'Thư viện Alovu <tuananhih271@gmail.com>'

# Sửa 'en-us' thành 'vi'
LANGUAGE_CODE = 'vi'

# Đảm bảo cài đặt i18n đang được bật
USE_I18N = True
USE_TZ = True

# 3. Cấu hình thời gian sống của Token (Nên để ở cuối file)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # Access token sống 60 phút
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # Refresh token sống 7 ngày
    'AUTH_HEADER_TYPES': ('Bearer',),               # Chuẩn header: Authorization: Bearer <token>
}

# Thêm vào cuối file
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', 'your-api-key-here')