"""
Django settings for library_system project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g(p@77ai!yd-v%9sc^&!#@3^ndu=#f2w(y*fnii_r$fzjjim3o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'library_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.dashboard_stats',
                'core.context_processors.notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'alovu_library', # Tên database chúng ta sẽ tạo trên XAMPP
        'USER': 'root',          # User mặc định của XAMPP
        'PASSWORD': '',          # Pass mặc định của XAMPP là rỗng
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', names 'utf8mb4'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'core.User'

STATIC_URL = '/static/'
# Khai báo đường dẫn thư mục static chung của toàn dự án
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

JAZZMIN_SETTINGS = {
    "site_title": "Admin Alovu",
    "site_header": "Alovu Library",
    "site_brand": "Thư viện Alovu",
    "welcome_sign": "Chào mừng Khanh đến với hệ thống quản trị",
    "copyright": "Alovu Library",
    "search_model": ["core.Book", "core.User"], 
    
    "topmenu_links": [
        {"name": "Trang chủ", "url": "admin:index", "permissions": ["core.view_user"]},
        {"name": "Thoát hệ thống", "url": "/logout/", "icon": "fas fa-sign-out-alt", "new_window": False},
        {"model": "core.User"},
    ],
    
    "user_menu_links": [
        {"name": "Thoát", "url": "/logout/", "icon": "fas fa-power-off text-danger"},
    ],
    
    "order_with_respect_to": [
        "core.Book", "core.Category", "core.Publisher", "core.BookImage",
        "core.BorrowTransaction", "core.Penalty", 
        "core.User", "core.Membership", "core.Wishlist", "core.Recommendation",
        "core.Review", "core.Notification", "core.ChatRoom", "core.Chat"
    ],
    
    "changeform_format": "vertical_tabs", 
    "default_theme_mode": "light", 
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    # Dùng nền trắng, chữ đậm để nút tài khoản admin hiện rõ ràng nhất
    "navbar": "navbar-white navbar-light", 
    "brand_colour": "navbar-orange", # Nền logo góc trái màu cam
    "accent": "accent-orange", # Màu viền và các điểm nhấn màu cam
    "sidebar": "sidebar-dark-primary", # Cột menu bên trái màu tối
    
    # Các thiết lập kích thước (giữ nguyên của Khanh)
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Khi gọi hàm logout, hệ thống sẽ tự tìm đến URL có name='login'
LOGOUT_REDIRECT_URL = 'login'