# Generated by Django 5.1.1 on 2026-03-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
