# Generated by Django 5.1.1 on 2026-03-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_borrowtransaction_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hạn trả'),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày trả thực tế'),
        ),
    ]
