# Generated by Django 5.1.1 on 2026-03-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_borrowtransaction_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Cuốn sách', 'verbose_name_plural': 'Kho Sách'},
        ),
        migrations.AlterModelOptions(
            name='borrowtransaction',
            options={'verbose_name': 'Giao dịch mượn', 'verbose_name_plural': 'Quản lý Mượn/Trả'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục sách', 'verbose_name_plural': 'Các Danh mục sách'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name': 'Phiếu phạt', 'verbose_name_plural': 'Danh sách Xử phạt'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Nhà xuất bản', 'verbose_name_plural': 'Các Nhà xuất bản'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Danh sách Người dùng'},
        ),
    ]
