# Generated by Django 5.1.1 on 2026-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_options_alter_borrowtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='Khu vực/Phòng'),
        ),
        migrations.AddField(
            model_name='book',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Tầng'),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kệ sách'),
        ),
    ]
