# Generated by Django 5.1.1 on 2026-03-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_book_area_book_floor_book_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dia_chi',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='user',
            name='lop',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lớp'),
        ),
        migrations.AddField(
            model_name='user',
            name='msv',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã sinh viên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
