# Generated by Django 5.1.1 on 2026-03-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_dia_chi_user_lop_user_msv_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán')], default='UNPAID', max_length=10, verbose_name='Trạng thái'),
        ),
    ]
