# Generated by Django 5.1.1 on 2026-03-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_penalty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
