# Generated by Django 5.1.1 on 2026-03-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COUNTER', 'Tại quầy'), ('TRANSFER', 'Chuyển khoản')], max_length=20, null=True),
        ),
    ]
