# Generated by Django 5.1.1 on 2026-03-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_penalty_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Điểm tích lũy'),
        ),
    ]
