# Generated by Django 5.1.1 on 2026-03-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày mượn'),
        ),
    ]
