# Generated by Django 5.1.1 on 2026-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_borrowtransaction_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('BORROWED', 'Đang mượn'), ('PENDING', 'Chờ xác nhận'), ('RETURNED', 'Đã trả'), ('OVERDUE', 'Quá hạn')], default='BORROWED', max_length=20),
        ),
    ]
