# Generated by Django 5.1.1 on 2026-03-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_borrowtransaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Tin nhắn Chat', 'verbose_name_plural': 'Lịch sử Tin nhắn'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Phòng Chat', 'verbose_name_plural': 'Danh sách Phòng Chat'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Hạng thành viên', 'verbose_name_plural': 'Quản lý Hạng thành viên'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Thông báo', 'verbose_name_plural': 'Hệ thống Thông báo'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Đề xuất sách', 'verbose_name_plural': 'Danh sách Đề xuất'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Danh sách Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Yêu thích', 'verbose_name_plural': 'Danh sách Yêu thích'},
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='payment_method',
            field=models.CharField(choices=[('FREE', 'Miễn phí'), ('CASH', 'Thanh toán tại quầy'), ('BANK', 'Chuyển khoản ngân hàng')], default='FREE', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
