# Generated by Django 5.1.1 on 2026-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_chat_options_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_file',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/'),
        ),
    ]
