# Generated by Django 5.1.1 on 2026-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hẹn lấy'),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='pickup_shift',
            field=models.CharField(blank=True, choices=[('SANG', 'Buổi Sáng (07:30 - 11:30)'), ('CHIEU', 'Buổi Chiều (13:00 - 17:00)')], max_length=10, null=True, verbose_name='Ca hẹn lấy'),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('BORROWED', 'Đang mượn'), ('PENDING', 'Chờ xác nhận'), ('RETURNED', 'Đã trả'), ('OVERDUE', 'Quá hạn'), ('CANCELLED', 'Đã hủy hẹn')], default='BORROWED', max_length=20),
        ),
    ]
