# Generated by Django 5.1.1 on 2026-04-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_borrowtransaction_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá gốc của sách'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá thuê sách (nếu có)'),
        ),
    ]
