# Generated by Django 5.1.1 on 2026-04-19 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_book_original_price_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên sự kiện')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Ảnh bìa')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết')),
                ('start_date', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('location', models.CharField(max_length=255, verbose_name='Địa điểm tổ chức')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='Giới hạn người tham gia (0 = Không giới hạn)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang mở')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
