# Generated by Django 5.1.1 on 2026-04-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_event_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='renewal_count',
            field=models.IntegerField(default=0, verbose_name='Số lần gia hạn'),
        ),
    ]
