# Generated by Django 5.1.1 on 2026-04-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Sự kiện', 'verbose_name_plural': 'Danh sách Sự kiện'},
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'verbose_name': 'Đăng ký sự kiện', 'verbose_name_plural': 'Danh sách Đăng ký Sự kiện'},
        ),
    ]
